In [10]:
import numpy as np
import pandas as pd

In [11]:
df_raw = pd.read_csv('train.csv')
df_train = df_raw

In [12]:
print(df_raw.isnull().sum())

id                               0
distance                         0
taxi_type                    12152
months_of_activity            3533
customer_score               12041
customer_score_confidence    12041
drop_location_type               0
ratings_given_by_cust            0
num_of_cancelled_trips           0
anon_var_1                   42419
anon_var_2                       0
anon_var_3                       0
sex                              0
pricing_category                 0
dtype: int64

In [13]:
d = pd.get_dummies(df_train, 
                   columns=['taxi_type', 'customer_score_confidence', 'drop_location_type', 'sex'], 
                   dummy_na=True)
d = d.drop(['id','anon_var_1'], axis=1)
d_raw = d.copy(deep=True)

In [14]:
# print(d.isnull().sum())

In [15]:
months_of_activity = d['months_of_activity']
customer_score = d['customer_score']
# df.fillna(df.mean(), inplace=True)

In [16]:
months_of_activity = months_of_activity.fillna(months_of_activity.median())
d['months_of_activity'] = months_of_activity
d_raw1 = d.copy(deep=True)

In [17]:
customer_score = customer_score.fillna(customer_score.mean())
d['customer_score'] = customer_score

In [18]:
# print(d.isnull().sum())
# print(d_raw1.isnull().sum())
# print(d_raw.isnull().sum())
# d_raw1

In [19]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge, LinearRegression
from sklearn.neural_network import MLPRegressor

In [20]:
data = d.drop(['customer_score','pricing_category'], axis=1)
label = d['customer_score']

In [21]:
x_train, x_test, y_train, y_test = train_test_split(data, label, test_size = 0.1)

In [22]:
# regressor = RandomForestRegressor(n_jobs=-1, n_estimators=100, warm_start=True, verbose=1)
regressor = MLPRegressor(verbose=True)

In [23]:
regressor.fit(x_train, y_train)

Iteration 1, loss = 0.73965000
Iteration 2, loss = 0.02677368
Iteration 3, loss = 0.02196214
Iteration 4, loss = 0.01770620
Iteration 5, loss = 0.01578984
Iteration 6, loss = 0.01544477
Iteration 7, loss = 0.01503300
Iteration 8, loss = 0.01499181
Iteration 9, loss = 0.01483548
Iteration 10, loss = 0.01465771
Iteration 11, loss = 0.01545313
Iteration 12, loss = 0.01590547
Iteration 13, loss = 0.01502370
Iteration 14, loss = 0.01592272
Iteration 15, loss = 0.01597412
Iteration 16, loss = 0.01589718
Iteration 17, loss = 0.01593093
Iteration 18, loss = 0.01642792
Iteration 19, loss = 0.01481421
Iteration 20, loss = 0.01620653
Iteration 21, loss = 0.01552202
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=True, warm_start=False)

In [24]:
pred = regressor.predict(x_train)
score = np.linalg.norm((y_train-pred)**2,ord=2)/pred.shape[0]
print(score)

0.00028949897223903923

In [25]:
pred = regressor.predict(x_test)
score = np.linalg.norm((y_test-pred)**2,ord=2)/pred.shape[0]
print(score)

0.0008006931658972253

In [26]:
customer_score_orig = d_raw1['customer_score']

In [27]:
indx_nan = np.array(customer_score_orig.isna())
indx_nan = np.where(indx_nan == True)[0]
indx_not_nan = np.where(indx_nan == False)[0]

In [28]:
d_raw1

,distance,months_of_activity,customer_score,ratings_given_by_cust,num_of_cancelled_trips,anon_var_2,anon_var_3,pricing_category,taxi_type_A,taxi_type_B,...,drop_location_type_I,drop_location_type_J,drop_location_type_K,drop_location_type_L,drop_location_type_M,drop_location_type_N,drop_location_type_nan,sex_Female,sex_Male,sex_nan
0,59.30,1.0,NaN,1.18625,0,50,71,2,0,0,...,0,0,0,0,0,0,0,0,1,0
1,20.68,0.0,2.79222,1.91750,1,50,65,2,0,1,...,0,0,0,0,0,0,0,0,1,0
2,64.83,1.0,2.97482,3.62125,0,49,84,2,0,1,...,0,0,0,0,0,0,0,0,1,0
3,25.51,0.0,2.90334,4.76750,2,43,60,3,0,0,...,0,0,0,0,0,0,0,1,0,0
4,20.16,6.0,2.62301,2.03875,0,52,71,3,0,0,...,0,0,0,0,0,0,0,1,0,0
5,16.07,0.0,2.23315,2.61625,3,52,66,1,1,0,...,0,0,0,0,0,0,0,1,0,0
6,62.67,5.0,2.91195,2.70375,1,59,95,1,1,0,...,0,0,0,0,0,0,0,0,1,0
7,61.80,10.0,2.88819,2.90375,0,51,70,1,1,0,...,0,0,0,0,0,0,0,1,0,0
8,50.22,10.0,2.64932,2.32375,0,49,82,2,0,1,...,0,0,0,0,0,0,0,0,1,0
9,47.68,2.0,2.62713,3.85250,0,46,58,3,0,0,...,0,0,0,0,0,0,0,1,0,0
10,47.79,2.0,2.90698,1.39625,1,52,90,3,0,0,...,0,0,0,0,0,0,0,0,1,0
11,18.25,5.0,2.69602,1.86750,1,53,77,2,0,0,...,0,0,0,0,0,0,0,0,1,0
12,91.61,10.0,3.09525,4.12500,0,50,67,3,0,1,...,0,0,0,0,0,0,0,0,1,0
13,90.96,10.0,NaN,1.62000,0,61,91,3,0,0,...,0,0,0,0,0,0,0,0,1,0
14,63.03,3.0,2.95138,3.06125,0,58,85,2,0,1,...,0,0,0,0,0,0,0,1,0,0
15,28.28,10.0,2.81862,2.92125,1,55,86,1,1,0,...,0,0,0,0,0,0,0,1,0,0
16,16.97,10.0,3.08221,1.50125,1,59,91,2,0,1,...,0,0,0,0,0,0,0,0,1,0
17,75.37,0.0,2.90538,4.21375,2,50,73,3,0,0,...,0,0,0,0,0,0,0,0,1,0
18,81.73,10.0,2.91318,2.92750,0,50,76,1,0,0,...,0,0,0,0,0,0,0,0,1,0
19,30.00,6.0,2.59192,2.72000,0,47,86,2,0,0,...,0,0,0,0,0,0,0,1,0,0
20,30.34,2.0,2.77153,4.40250,0,45,66,2,0,0,...,0,0,0,0,0,0,0,0,1,0
21,3.47,5.0,2.54327,1.27625,1,54,66,2,0,1,...,0,0,0,0,0,0,0,0,1,0
22,27.32,9.0,2.42415,2.71000,0,45,58,2,0,1,...,0,0,0,0,0,0,0,0,1,0
23,29.90,3.0,NaN,3.01750,0,50,70,1,0,1,...,0,0,0,0,0,0,0,1,0,0
24,54.37,2.0,2.84372,2.02500,1,50,76,3,0,0,...,0,0,0,0,0,0,0,0,1,0
25,30.79,0.0,NaN,1.48125,3,54,74,2,0,0,...,0,0,0,0,0,0,0,1,0,0
26,31.38,10.0,2.80479,0.82375,0,53,88,2,0,0,...,0,0,0,0,0,0,0,0,1,0
27,29.65,10.0,3.08826,2.71625,1,57,84,3,0,0,...,0,0,0,0,0,0,0,0,1,0
28,33.14,10.0,2.59571,2.46125,0,45,60,2,0,0,...,0,0,0,0,0,0,0,0,1,0
29,55.14,10.0,2.93183,1.04500,0,56,89,3,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78967,10.47,6.0,2.90164,2.86250,1,63,88,3,0,0,...,0,0,0,0,0,0,0,0,1,0
78968,13.29,5.0,2.69374,2.15875,3,56,95,2,0,0,...,0,0,0,0,0,0,0,0,1,0
78969,43.50,6.0,2.65869,1.38250,0,58,80,2,0,0,...,0,0,0,0,0,0,0,0,1,0
78970,108.21,1.0,3.60307,2.90000,0,56,97,3,0,0,...,0,0,0,0,0,0,0,0,1,0
78971,92.94,6.0,NaN,3.62125,0,57,98,1,1,0,...,0,0,0,0,0,0,0,0,1,0
78972,11.72,3.0,3.03778,2.58750,1,58,86,2,0,0,...,0,0,0,0,0,0,0,0,1,0
78973,63.65,10.0,2.80693,3.60125,1,47,75,3,0,0,...,0,0,0,0,0,0,0,1,0,0
78974,107.32,10.0,3.13175,1.76250,0,62,92,3,0,0,...,0,0,0,0,0,0,0,1,0,0
78975,50.75,10.0,3.02401,2.81625,0,50,85,1,0,0,...,0,0,0,0,0,0,0,0,1,0
78976,47.14,6.0,2.85494,2.56625,5,53,73,2,0,0,...,0,0,0,0,0,0,0,0,1,0
78977,36.84,0.0,2.74683,2.88125,0,54,107,2,0,0,...,0,0,0,0,0,0,0,0,1,0
78978,22.81,10.0,2.53681,2.66000,0,49,65,2,0,1,...,0,0,0,0,0,0,0,1,0,0
78979,108.14,10.0,3.05961,3.95250,2,52,83,3,0,0,...,0,0,0,1,0,0,0,0,1,0
78980,15.44,6.0,2.66567,1.96500,0,47,74,2,0,0,...,0,0,0,0,0,0,0,1,0,0
78981,23.18,3.0,2.63218,1.73375,0,52,68,2,0,0,...,0,0,0,0,0,0,0,0,1,0
78982,74.20,9.0,2.96172,2.43875,0,55,100,1,1,0,...,0,0,0,0,0,0,0,0,1,0
78983,4.67,4.0,2.76448,3.31250,0,62,85,2,0,1,...,0,0,0,0,0,0,0,1,0,0
78984,91.79,10.0,3.02311,3.06875,1,48,61,3,1,0,...,0,0,0,0,0,0,0,1,0,0
78985,57.19,5.0,2.78598,2.68500,0,47,82,1,1,0,...,0,0,0,0,0,0,0,0,1,0
78986,56.58,10.0,3.10025,2.80375,0,49,75,2,0,1,...,0,0,0,0,0,0,0,1,0,0
78987,42.25,6.0,3.02773,2.42375,1,57,91,2,0,1,...,0,0,0,0,0,0,0,1,0,0
78988,18.42,4.0,2.60492,1.39250,2,53,81,2,0,0,...,0,0,0,0,0,0,0,1,0,0
78989,62.06,10.0,2.79133,3.96875,0,47,71,2,0,0,...,0,0,0,0,0,0,0,0,1,0
78990,8.30,6.0,2.32079,3.96500,0,47,61,3,0,0,...,0,0,0,0,0,0,0,0,1,0
78991,69.29,10.0,2.77887,1.59000,0,53,74,3,0,0,...,0,0,0,0,0,0,0,0,1,0
78992,10.69,0.0,2.38653,3.27250,0,44,68,2,0,1,...,0,0,0,0,0,0,0,0,1,0
78993,31.58,10.0,2.61104,1.41125,1,49,68,2,0,1,...,0,0,0,0,0,0,0,1,0,0
78994,13.11,6.0,2.65354,3.54375,0,48,63,2,0,1,...,0,0,0,0,0,0,0,0,1,0
78995,63.79,10.0,NaN,3.60125,0,51,74,2,0,0,...,0,0,0,0,0,0,0,0,1,0
78996,30.46,10.0,2.74367,2.69250,1,48,64,3,0,0,...,0,0,0,0,0,0,0,0,1,0

In [29]:
customer_score_pred = customer_score_orig
temp_data = np.array(d_raw1.drop(['customer_score','pricing_category'],axis=1))[indx_nan,:]
print(temp_data.shape)
customer_score_pred[indx_nan] = regressor.predict(temp_data)

(12041, 34)

/home/supreet/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [30]:
print(d_raw1.isnull().sum())

distance                         0
months_of_activity               0
customer_score                   0
ratings_given_by_cust            0
num_of_cancelled_trips           0
anon_var_2                       0
anon_var_3                       0
pricing_category                 0
taxi_type_A                      0
taxi_type_B                      0
taxi_type_C                      0
taxi_type_D                      0
taxi_type_E                      0
taxi_type_nan                    0
customer_score_confidence_A      0
customer_score_confidence_B      0
customer_score_confidence_C      0
customer_score_confidence_nan    0
drop_location_type_A             0
drop_location_type_B             0
drop_location_type_C             0
drop_location_type_D             0
drop_location_type_E             0
drop_location_type_F             0
drop_location_type_G             0
drop_location_type_H             0
drop_location_type_I             0
drop_location_type_J             0
drop_location_type_K             0
drop_location_type_L             0
drop_location_type_M             0
drop_location_type_N             0
drop_location_type_nan           0
sex_Female                       0
sex_Male                         0
sex_nan                          0
dtype: int64

In [22]:
d_raw = d_raw1.copy(deep=True)

In [23]:
d_raw['months_of_activity'] = df_raw['months_of_activity']

In [24]:
print(d_raw.isnull().sum())

distance                            0
months_of_activity               3533
customer_score                      0
ratings_given_by_cust               0
num_of_cancelled_trips              0
anon_var_2                          0
anon_var_3                          0
pricing_category                    0
taxi_type_A                         0
taxi_type_B                         0
taxi_type_C                         0
taxi_type_D                         0
taxi_type_E                         0
taxi_type_nan                       0
customer_score_confidence_A         0
customer_score_confidence_B         0
customer_score_confidence_C         0
customer_score_confidence_nan       0
drop_location_type_A                0
drop_location_type_B                0
drop_location_type_C                0
drop_location_type_D                0
drop_location_type_E                0
drop_location_type_F                0
drop_location_type_G                0
drop_location_type_H                0
drop_location_type_I                0
drop_location_type_J                0
drop_location_type_K                0
drop_location_type_L                0
drop_location_type_M                0
drop_location_type_N                0
drop_location_type_nan              0
sex_Female                          0
sex_Male                            0
sex_nan                             0
dtype: int64

In [25]:
data = d_raw.drop(['months_of_activity','pricing_category'], axis=1)
label = d['months_of_activity']

In [26]:
x_train, x_test, y_train, y_test = train_test_split(data, label, test_size = 0.1)

In [27]:
regressor_2 = MLPRegressor()

In [28]:
regressor_2.fit(x_train, y_train)

/home/supreet/.local/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [29]:
pred = regressor.predict(x_train)
score = np.linalg.norm((y_train-pred)**2,ord=2)/pred.shape[0]
print(score)

0.1143160118731042

In [30]:
pred = regressor.predict(x_test)
score = np.linalg.norm((y_test-pred)**2,ord=2)/pred.shape[0]
print(score)

0.3456551637224594

In [31]:
months_of_activity_orig = d_raw['months_of_activity']

In [32]:
indx_nan = np.array(months_of_activity_orig.isna())
indx_nan = np.where(indx_nan == True)[0]
indx_not_nan = np.where(indx_nan == False)[0]

In [33]:
months_of_activity_pred = months_of_activity_orig
temp_data = np.array(d_raw.drop(['months_of_activity','pricing_category'],axis=1))[indx_nan,:]
print(temp_data.shape)
months_of_activity_pred[indx_nan] = regressor.predict(temp_data)

(3533, 34)

/home/supreet/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [34]:
print(d_raw.isnull().sum())

distance                         0
months_of_activity               0
customer_score                   0
ratings_given_by_cust            0
num_of_cancelled_trips           0
anon_var_2                       0
anon_var_3                       0
pricing_category                 0
taxi_type_A                      0
taxi_type_B                      0
taxi_type_C                      0
taxi_type_D                      0
taxi_type_E                      0
taxi_type_nan                    0
customer_score_confidence_A      0
customer_score_confidence_B      0
customer_score_confidence_C      0
customer_score_confidence_nan    0
drop_location_type_A             0
drop_location_type_B             0
drop_location_type_C             0
drop_location_type_D             0
drop_location_type_E             0
drop_location_type_F             0
drop_location_type_G             0
drop_location_type_H             0
drop_location_type_I             0
drop_location_type_J             0
drop_location_type_K             0
drop_location_type_L             0
drop_location_type_M             0
drop_location_type_N             0
drop_location_type_nan           0
sex_Female                       0
sex_Male                         0
sex_nan                          0
dtype: int64

In [35]:
#df

NameError: name 'df' is not defined

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [31]:
data = d_raw.drop(['pricing_category'], axis=1)
label = d_raw['pricing_category']

In [32]:
x_train, x_test, y_train, y_test = train_test_split(data, label, test_size = 0.3)

In [ ]:
clf = RandomForestClassifier(n_jobs=4, max_depth=11, n_estimators=100)

In [ ]:
clf.fit(x_train, y_train)

In [ ]:
print(clf.score(x_train, y_train))
print(clf.score(x_test, y_test))

In [ ]:
# data

In [33]:
df_test = pd.read_csv('test.csv')
df_test = pd.get_dummies(df_test, columns=['taxi_type', 'customer_score_confidence', 'drop_location_type', 'sex'], dummy_na=True)
df_test_id = df_test['id']
df_test = df_test.drop(['anon_var_1','id'],axis=1)
df_test1 = df_test.copy(deep=True)
print(df_test.shape)

(52665, 35)

In [34]:
print(df_test.isnull().sum())

distance                            0
months_of_activity               2387
customer_score                   8152
ratings_given_by_cust               0
num_of_cancelled_trips              0
anon_var_2                          0
anon_var_3                          0
taxi_type_A                         0
taxi_type_B                         0
taxi_type_C                         0
taxi_type_D                         0
taxi_type_E                         0
taxi_type_nan                       0
customer_score_confidence_A         0
customer_score_confidence_B         0
customer_score_confidence_C         0
customer_score_confidence_nan       0
drop_location_type_A                0
drop_location_type_B                0
drop_location_type_C                0
drop_location_type_D                0
drop_location_type_E                0
drop_location_type_F                0
drop_location_type_G                0
drop_location_type_H                0
drop_location_type_I                0
drop_location_type_J                0
drop_location_type_K                0
drop_location_type_L                0
drop_location_type_M                0
drop_location_type_N                0
drop_location_type_nan              0
sex_Female                          0
sex_Male                            0
sex_nan                             0
dtype: int64

In [35]:
months_of_activity_t = df_test['months_of_activity']
months_of_activity_t.fillna(months_of_activity.median(), inplace=True)
df_test['months_of_activity'] = months_of_activity_t

In [36]:
customer_score_orig_t = df_test['customer_score']

indx_nan_t = np.array(customer_score_orig_t.isna())
indx_nan_t = np.where(indx_nan_t == True)[0]
indx_not_nan_t = np.where(indx_nan_t == False)[0]

customer_score_pred_t = customer_score_orig_t
temp_data_t = np.array(df_test.drop(['customer_score'],axis=1))[indx_nan_t,:]
customer_score_pred_t[indx_nan_t] = regressor.predict(temp_data_t)

/home/supreet/.local/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [40]:
df_test['months_of_activity'] = df_test1['months_of_activity']
print(df_test.isnull().sum())

distance                            0
months_of_activity               2387
customer_score                      0
ratings_given_by_cust               0
num_of_cancelled_trips              0
anon_var_2                          0
anon_var_3                          0
taxi_type_A                         0
taxi_type_B                         0
taxi_type_C                         0
taxi_type_D                         0
taxi_type_E                         0
taxi_type_nan                       0
customer_score_confidence_A         0
customer_score_confidence_B         0
customer_score_confidence_C         0
customer_score_confidence_nan       0
drop_location_type_A                0
drop_location_type_B                0
drop_location_type_C                0
drop_location_type_D                0
drop_location_type_E                0
drop_location_type_F                0
drop_location_type_G                0
drop_location_type_H                0
drop_location_type_I                0
drop_location_type_J                0
drop_location_type_K                0
drop_location_type_L                0
drop_location_type_M                0
drop_location_type_N                0
drop_location_type_nan              0
sex_Female                          0
sex_Male                            0
sex_nan                             0
dtype: int64

In [41]:
months_of_activity_orig_t = df_test['months_of_activity']

indx_nan_t = np.array(months_of_activity_orig_t.isna())
indx_nan_t = np.where(indx_nan_t == True)[0]
indx_not_nan_t = np.where(indx_nan_t == False)[0]
# print(indx_nan_t)
months_of_activity_pred_t = months_of_activity_orig_t
temp_data_t = np.array(df_test.drop(['months_of_activity'],axis=1))[indx_nan_t,:]
months_of_activity_pred_t[indx_nan_t] = regressor_2.predict(temp_data_t)

/home/supreet/.local/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [37]:
print(df_test.isnull().sum())

distance                         0
months_of_activity               0
customer_score                   0
ratings_given_by_cust            0
num_of_cancelled_trips           0
anon_var_2                       0
anon_var_3                       0
taxi_type_A                      0
taxi_type_B                      0
taxi_type_C                      0
taxi_type_D                      0
taxi_type_E                      0
taxi_type_nan                    0
customer_score_confidence_A      0
customer_score_confidence_B      0
customer_score_confidence_C      0
customer_score_confidence_nan    0
drop_location_type_A             0
drop_location_type_B             0
drop_location_type_C             0
drop_location_type_D             0
drop_location_type_E             0
drop_location_type_F             0
drop_location_type_G             0
drop_location_type_H             0
drop_location_type_I             0
drop_location_type_J             0
drop_location_type_K             0
drop_location_type_L             0
drop_location_type_M             0
drop_location_type_N             0
drop_location_type_nan           0
sex_Female                       0
sex_Male                         0
sex_nan                          0
dtype: int64

In [43]:
testY_i = clf.predict(df_test)
print(testY_i.shape)
testY_s = []
for x in testY_i:
    testY_s.append(float(x))
# Write the predictions to a CSV file 
submission = pd.DataFrame(
    {'id': df_test_id, 'pricing_category': testY_s},
    columns = ['id', 'pricing_category'])
submission.to_csv('submission_hack.csv', index = False)

NameError: name 'clf' is not defined

## xgboost

In [38]:
from sklearn.model_selection import RandomizedSearchCV

def report_best_scores(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.3f} (std: {1:.3f})".format(
                  results['mean_test_score'][candidate],
                  results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")

In [39]:
import xgboost as xgb

In [40]:
x_train, x_test, y_train, y_test = train_test_split(data, label, test_size = 0)

In [41]:
xgb_model = xgb.XGBClassifier(objective="multi:softprob", n_jobs=6
                              , booster='gbtree', learning_rate=0.1)
y_train

6540     2
34420    3
8593     1
12788    2
47210    3
42000    2
69503    1
55617    3
74850    2
54624    3
38836    2
43774    2
44848    2
33945    2
58520    2
9022     1
53504    3
4206     1
61618    1
14663    2
32676    2
22543    1
64817    3
19777    2
61490    2
57837    3
55271    3
45596    2
39219    2
15222    2
        ..
32756    2
5178     2
36549    3
8201     2
78550    2
30993    3
44272    1
78314    2
33929    3
68543    2
8006     1
73707    3
51161    3
56733    2
58788    2
69458    2
29404    3
3343     2
50547    2
8762     2
24779    2
31738    1
29915    2
29418    2
40010    3
66944    2
7971     3
41945    1
53506    3
57600    2
Name: pricing_category, Length: 78997, dtype: int64

In [44]:
xgb_model.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=6, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [56]:
xgb_model.score(x_train, y_train)

0.6970264693595959

In [42]:
from scipy.stats import uniform, randint
params = {
    "colsample_bytree": uniform(0.7, 0.3),
    "gamma": uniform(0, 0.5),
    "learning_rate": uniform(0.03, 0.3), # default 0.1 
    "max_depth": randint(2, 6), # default 3
    "n_estimators": randint(100, 150), # default 100
    "subsample": uniform(0.6, 0.4)
}
search = RandomizedSearchCV(xgb_model, param_distributions=params, cv=3,  n_jobs=1, return_train_score=True)
search.fit(x_train, y_train)

RandomizedSearchCV(cv=3, error_score='raise-deprecating',
          estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=6, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1),
          fit_params=None, iid='warn', n_iter=10, n_jobs=1,
          param_distributions={'colsample_bytree': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fcf42dce2b0>, 'gamma': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fcf42dce080>, 'learning_rate': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fcf42dce6a0>, 'max_depth': <sci...x7fcf42dce668>, 'subsample': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fcf0b0da208>},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score=True, scoring=None, verbose=0)

In [43]:
report_best_scores(search.cv_results_, 1)

Model with rank: 1
Mean validation score: 0.699 (std: 0.003)
Parameters: {'colsample_bytree': 0.7607677255012393, 'gamma': 0.3459204700714696, 'learning_rate': 0.1720898454178224, 'max_depth': 5, 'n_estimators': 140, 'subsample': 0.9102786976218932}

In [45]:
xgb_model2 = xgb.XGBClassifier(objective="multi:softprob", n_jobs=6 , 
                               colsample_bytree=0.7607677255012393 , 
                               gamma=0.3459204700714696 ,
                               learning_rate= 0.1720898454178224 ,
                               max_depth=5,n_estimators=140 , 
                               subsample= 0.9102786976218932)
xgb_model2.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.7607677255012393, gamma=0.3459204700714696,
       learning_rate=0.1720898454178224, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=140, n_jobs=6,
       nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=0.9102786976218932)

In [46]:
testY_i = xgb_model2.predict(df_test)
print(testY_i.shape)
testY_s = []
for x in testY_i:
    testY_s.append(float(x))
# Write the predictions to a CSV file 
submission = pd.DataFrame(
    {'id': df_test_id, 'pricing_category': testY_s},
    columns = ['id', 'pricing_category'])
submission.to_csv('submission_grad_boost.csv', index = False)

(52665,)