In [1]:
import numpy as np
import pandas as pd

In [2]:
df_raw = pd.read_csv('train.csv')
df_train = df_raw

In [3]:
print(df_raw.isnull().sum())

id                               0
distance                         0
taxi_type                    12152
months_of_activity            3533
customer_score               12041
customer_score_confidence    12041
drop_location_type               0
ratings_given_by_cust            0
num_of_cancelled_trips           0
anon_var_1                   42419
anon_var_2                       0
anon_var_3                       0
sex                              0
pricing_category                 0
dtype: int64

In [4]:
d = pd.get_dummies(df_train, 
                   columns=['taxi_type', 'customer_score_confidence', 'drop_location_type', 'sex'], 
                   dummy_na=True)
d = d.drop(['id','anon_var_1'], axis=1)
d_raw = d.copy(deep=True)

In [5]:
# print(d.isnull().sum())

In [6]:
months_of_activity = d['months_of_activity']
customer_score = d['customer_score']
# df.fillna(df.mean(), inplace=True)

In [7]:
months_of_activity = months_of_activity.fillna(months_of_activity.mean())
d['months_of_activity'] = months_of_activity
d_raw1 = d.copy(deep=True)

In [8]:
customer_score = customer_score.fillna(customer_score.mean())
d['customer_score'] = customer_score

In [9]:
# print(d.isnull().sum())
# print(d_raw1.isnull().sum())
# print(d_raw.isnull().sum())
# d_raw1

In [10]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge, LinearRegression
from sklearn.neural_network import MLPRegressor

In [11]:
data = d.drop(['customer_score','pricing_category'], axis=1)
label = d['customer_score']

In [12]:
x_train, x_test, y_train, y_test = train_test_split(data, label, test_size = 0.1)

In [13]:
# regressor = RandomForestRegressor(n_jobs=-1, n_estimators=100, warm_start=True, verbose=1)
regressor = MLPRegressor(verbose=False)

In [14]:
regressor.fit(x_train, y_train)

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [15]:
pred = regressor.predict(x_train)
score = np.linalg.norm((y_train-pred)**2,ord=2)/pred.shape[0]
print(score)

0.0002247232300754534

In [16]:
pred = regressor.predict(x_test)
score = np.linalg.norm((y_test-pred)**2,ord=2)/pred.shape[0]
print(score)

0.0006555586664657421

In [17]:
customer_score_orig = d_raw1['customer_score']

In [18]:
indx_nan = np.array(customer_score_orig.isna())
indx_nan = np.where(indx_nan == True)[0]
indx_not_nan = np.where(indx_nan == False)[0]

In [19]:
d_raw1

,distance,months_of_activity,customer_score,ratings_given_by_cust,num_of_cancelled_trips,anon_var_2,anon_var_3,pricing_category,taxi_type_A,taxi_type_B,...,drop_location_type_I,drop_location_type_J,drop_location_type_K,drop_location_type_L,drop_location_type_M,drop_location_type_N,drop_location_type_nan,sex_Female,sex_Male,sex_nan
0,59.30,1.000000,NaN,1.18625,0,50,71,2,0,0,...,0,0,0,0,0,0,0,0,1,0
1,20.68,0.000000,2.79222,1.91750,1,50,65,2,0,1,...,0,0,0,0,0,0,0,0,1,0
2,64.83,1.000000,2.97482,3.62125,0,49,84,2,0,1,...,0,0,0,0,0,0,0,0,1,0
3,25.51,0.000000,2.90334,4.76750,2,43,60,3,0,0,...,0,0,0,0,0,0,0,1,0,0
4,20.16,6.000000,2.62301,2.03875,0,52,71,3,0,0,...,0,0,0,0,0,0,0,1,0,0
5,16.07,0.000000,2.23315,2.61625,3,52,66,1,1,0,...,0,0,0,0,0,0,0,1,0,0
6,62.67,5.000000,2.91195,2.70375,1,59,95,1,1,0,...,0,0,0,0,0,0,0,0,1,0
7,61.80,10.000000,2.88819,2.90375,0,51,70,1,1,0,...,0,0,0,0,0,0,0,1,0,0
8,50.22,10.000000,2.64932,2.32375,0,49,82,2,0,1,...,0,0,0,0,0,0,0,0,1,0
9,47.68,2.000000,2.62713,3.85250,0,46,58,3,0,0,...,0,0,0,0,0,0,0,1,0,0
10,47.79,2.000000,2.90698,1.39625,1,52,90,3,0,0,...,0,0,0,0,0,0,0,0,1,0
11,18.25,5.000000,2.69602,1.86750,1,53,77,2,0,0,...,0,0,0,0,0,0,0,0,1,0
12,91.61,10.000000,3.09525,4.12500,0,50,67,3,0,1,...,0,0,0,0,0,0,0,0,1,0
13,90.96,10.000000,NaN,1.62000,0,61,91,3,0,0,...,0,0,0,0,0,0,0,0,1,0
14,63.03,3.000000,2.95138,3.06125,0,58,85,2,0,1,...,0,0,0,0,0,0,0,1,0,0
15,28.28,10.000000,2.81862,2.92125,1,55,86,1,1,0,...,0,0,0,0,0,0,0,1,0,0
16,16.97,10.000000,3.08221,1.50125,1,59,91,2,0,1,...,0,0,0,0,0,0,0,0,1,0
17,75.37,0.000000,2.90538,4.21375,2,50,73,3,0,0,...,0,0,0,0,0,0,0,0,1,0
18,81.73,10.000000,2.91318,2.92750,0,50,76,1,0,0,...,0,0,0,0,0,0,0,0,1,0
19,30.00,6.014179,2.59192,2.72000,0,47,86,2,0,0,...,0,0,0,0,0,0,0,1,0,0
20,30.34,2.000000,2.77153,4.40250,0,45,66,2,0,0,...,0,0,0,0,0,0,0,0,1,0
21,3.47,5.000000,2.54327,1.27625,1,54,66,2,0,1,...,0,0,0,0,0,0,0,0,1,0
22,27.32,9.000000,2.42415,2.71000,0,45,58,2,0,1,...,0,0,0,0,0,0,0,0,1,0
23,29.90,3.000000,NaN,3.01750,0,50,70,1,0,1,...,0,0,0,0,0,0,0,1,0,0
24,54.37,2.000000,2.84372,2.02500,1,50,76,3,0,0,...,0,0,0,0,0,0,0,0,1,0
25,30.79,0.000000,NaN,1.48125,3,54,74,2,0,0,...,0,0,0,0,0,0,0,1,0,0
26,31.38,10.000000,2.80479,0.82375,0,53,88,2,0,0,...,0,0,0,0,0,0,0,0,1,0
27,29.65,10.000000,3.08826,2.71625,1,57,84,3,0,0,...,0,0,0,0,0,0,0,0,1,0
28,33.14,10.000000,2.59571,2.46125,0,45,60,2,0,0,...,0,0,0,0,0,0,0,0,1,0
29,55.14,10.000000,2.93183,1.04500,0,56,89,3,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78967,10.47,6.000000,2.90164,2.86250,1,63,88,3,0,0,...,0,0,0,0,0,0,0,0,1,0
78968,13.29,5.000000,2.69374,2.15875,3,56,95,2,0,0,...,0,0,0,0,0,0,0,0,1,0
78969,43.50,6.000000,2.65869,1.38250,0,58,80,2,0,0,...,0,0,0,0,0,0,0,0,1,0
78970,108.21,1.000000,3.60307,2.90000,0,56,97,3,0,0,...,0,0,0,0,0,0,0,0,1,0
78971,92.94,6.000000,NaN,3.62125,0,57,98,1,1,0,...,0,0,0,0,0,0,0,0,1,0
78972,11.72,3.000000,3.03778,2.58750,1,58,86,2,0,0,...,0,0,0,0,0,0,0,0,1,0
78973,63.65,10.000000,2.80693,3.60125,1,47,75,3,0,0,...,0,0,0,0,0,0,0,1,0,0
78974,107.32,10.000000,3.13175,1.76250,0,62,92,3,0,0,...,0,0,0,0,0,0,0,1,0,0
78975,50.75,10.000000,3.02401,2.81625,0,50,85,1,0,0,...,0,0,0,0,0,0,0,0,1,0
78976,47.14,6.000000,2.85494,2.56625,5,53,73,2,0,0,...,0,0,0,0,0,0,0,0,1,0
78977,36.84,0.000000,2.74683,2.88125,0,54,107,2,0,0,...,0,0,0,0,0,0,0,0,1,0
78978,22.81,10.000000,2.53681,2.66000,0,49,65,2,0,1,...,0,0,0,0,0,0,0,1,0,0
78979,108.14,10.000000,3.05961,3.95250,2,52,83,3,0,0,...,0,0,0,1,0,0,0,0,1,0
78980,15.44,6.014179,2.66567,1.96500,0,47,74,2,0,0,...,0,0,0,0,0,0,0,1,0,0
78981,23.18,3.000000,2.63218,1.73375,0,52,68,2,0,0,...,0,0,0,0,0,0,0,0,1,0
78982,74.20,9.000000,2.96172,2.43875,0,55,100,1,1,0,...,0,0,0,0,0,0,0,0,1,0
78983,4.67,4.000000,2.76448,3.31250,0,62,85,2,0,1,...,0,0,0,0,0,0,0,1,0,0
78984,91.79,10.000000,3.02311,3.06875,1,48,61,3,1,0,...,0,0,0,0,0,0,0,1,0,0
78985,57.19,5.000000,2.78598,2.68500,0,47,82,1,1,0,...,0,0,0,0,0,0,0,0,1,0
78986,56.58,10.000000,3.10025,2.80375,0,49,75,2,0,1,...,0,0,0,0,0,0,0,1,0,0
78987,42.25,6.000000,3.02773,2.42375,1,57,91,2,0,1,...,0,0,0,0,0,0,0,1,0,0
78988,18.42,4.000000,2.60492,1.39250,2,53,81,2,0,0,...,0,0,0,0,0,0,0,1,0,0
78989,62.06,10.000000,2.79133,3.96875,0,47,71,2,0,0,...,0,0,0,0,0,0,0,0,1,0
78990,8.30,6.014179,2.32079,3.96500,0,47,61,3,0,0,...,0,0,0,0,0,0,0,0,1,0
78991,69.29,10.000000,2.77887,1.59000,0,53,74,3,0,0,...,0,0,0,0,0,0,0,0,1,0
78992,10.69,0.000000,2.38653,3.27250,0,44,68,2,0,1,...,0,0,0,0,0,0,0,0,1,0
78993,31.58,10.000000,2.61104,1.41125,1,49,68,2,0,1,...,0,0,0,0,0,0,0,1,0,0
78994,13.11,6.000000,2.65354,3.54375,0,48,63,2,0,1,...,0,0,0,0,0,0,0,0,1,0
78995,63.79,10.000000,NaN,3.60125,0,51,74,2,0,0,...,0,0,0,0,0,0,0,0,1,0
78996,30.46,10.000000,2.74367,2.69250,1,48,64,3,0,0,...,0,0,0,0,0,0,0,0,1,0

In [20]:
customer_score_pred = customer_score_orig
temp_data = np.array(d_raw1.drop(['customer_score','pricing_category'],axis=1))[indx_nan,:]
print(temp_data.shape)
customer_score_pred[indx_nan] = regressor.predict(temp_data)

(12041, 34)

/home/supreet/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [21]:
print(d_raw1.isnull().sum())

distance                         0
months_of_activity               0
customer_score                   0
ratings_given_by_cust            0
num_of_cancelled_trips           0
anon_var_2                       0
anon_var_3                       0
pricing_category                 0
taxi_type_A                      0
taxi_type_B                      0
taxi_type_C                      0
taxi_type_D                      0
taxi_type_E                      0
taxi_type_nan                    0
customer_score_confidence_A      0
customer_score_confidence_B      0
customer_score_confidence_C      0
customer_score_confidence_nan    0
drop_location_type_A             0
drop_location_type_B             0
drop_location_type_C             0
drop_location_type_D             0
drop_location_type_E             0
drop_location_type_F             0
drop_location_type_G             0
drop_location_type_H             0
drop_location_type_I             0
drop_location_type_J             0
drop_location_type_K             0
drop_location_type_L             0
drop_location_type_M             0
drop_location_type_N             0
drop_location_type_nan           0
sex_Female                       0
sex_Male                         0
sex_nan                          0
dtype: int64

In [22]:
d_raw = d_raw1.copy(deep=True)

In [23]:
d_raw['months_of_activity'] = df_raw['months_of_activity']

In [24]:
print(d_raw.isnull().sum())

distance                            0
months_of_activity               3533
customer_score                      0
ratings_given_by_cust               0
num_of_cancelled_trips              0
anon_var_2                          0
anon_var_3                          0
pricing_category                    0
taxi_type_A                         0
taxi_type_B                         0
taxi_type_C                         0
taxi_type_D                         0
taxi_type_E                         0
taxi_type_nan                       0
customer_score_confidence_A         0
customer_score_confidence_B         0
customer_score_confidence_C         0
customer_score_confidence_nan       0
drop_location_type_A                0
drop_location_type_B                0
drop_location_type_C                0
drop_location_type_D                0
drop_location_type_E                0
drop_location_type_F                0
drop_location_type_G                0
drop_location_type_H                0
drop_location_type_I                0
drop_location_type_J                0
drop_location_type_K                0
drop_location_type_L                0
drop_location_type_M                0
drop_location_type_N                0
drop_location_type_nan              0
sex_Female                          0
sex_Male                            0
sex_nan                             0
dtype: int64

In [25]:
data = d_raw.drop(['months_of_activity','pricing_category'], axis=1)
label = d['months_of_activity']

In [26]:
x_train, x_test, y_train, y_test = train_test_split(data, label, test_size = 0.1)

In [27]:
regressor_2 = MLPRegressor(verbose=True)

In [28]:
regressor_2.fit(x_train, y_train)

Iteration 1, loss = 6.32458924
Iteration 2, loss = 6.20966180
Iteration 3, loss = 6.18233236
Iteration 4, loss = 6.15362097
Iteration 5, loss = 6.11203071
Iteration 6, loss = 6.11464569
Iteration 7, loss = 6.09156060
Iteration 8, loss = 6.07467726
Iteration 9, loss = 6.05860829
Iteration 10, loss = 6.07535150
Iteration 11, loss = 6.06563334
Iteration 12, loss = 6.05322852
Iteration 13, loss = 6.06832851
Iteration 14, loss = 6.04592608
Iteration 15, loss = 6.05668423
Iteration 16, loss = 6.05477550
Iteration 17, loss = 6.05567799
Iteration 18, loss = 6.03248749
Iteration 19, loss = 6.03818531
Iteration 20, loss = 6.04970528
Iteration 21, loss = 6.03919462
Iteration 22, loss = 6.02889318
Iteration 23, loss = 6.04262817
Iteration 24, loss = 6.02593570
Iteration 25, loss = 6.02817476
Iteration 26, loss = 6.02071338
Iteration 27, loss = 6.03043720
Iteration 28, loss = 6.04283577
Iteration 29, loss = 6.02725756
Iteration 30, loss = 6.04276054
Iteration 31, loss = 6.03105461
Iteration 32, loss = 6.02518700
Iteration 33, loss = 6.02045687
Iteration 34, loss = 6.01607337
Iteration 35, loss = 6.02647501
Iteration 36, loss = 6.03528807
Iteration 37, loss = 6.03120472
Iteration 38, loss = 6.01881648
Iteration 39, loss = 6.01425700
Iteration 40, loss = 6.01363443
Iteration 41, loss = 6.01668755
Iteration 42, loss = 6.01225917
Iteration 43, loss = 6.00415867
Iteration 44, loss = 6.02559112
Iteration 45, loss = 6.01521035
Iteration 46, loss = 6.00493607
Iteration 47, loss = 6.00528343
Iteration 48, loss = 6.01471293
Iteration 49, loss = 6.00950971
Iteration 50, loss = 6.00821067
Iteration 51, loss = 6.00862442
Iteration 52, loss = 6.01203484
Iteration 53, loss = 6.01322765
Iteration 54, loss = 6.00144639
Iteration 55, loss = 6.00732766
Iteration 56, loss = 5.99708166
Iteration 57, loss = 6.00627833
Iteration 58, loss = 6.02870589
Iteration 59, loss = 5.99953214
Iteration 60, loss = 6.00050533
Iteration 61, loss = 5.99287096
Iteration 62, loss = 5.99480509
Iteration 63, loss = 5.99834225
Iteration 64, loss = 6.00006876
Iteration 65, loss = 6.00033418
Iteration 66, loss = 5.99198707
Iteration 67, loss = 5.99556393
Iteration 68, loss = 5.98706122
Iteration 69, loss = 6.00023062
Iteration 70, loss = 5.98623069
Iteration 71, loss = 5.99303027
Iteration 72, loss = 5.98923063
Iteration 73, loss = 5.98585111
Iteration 74, loss = 5.98590223
Iteration 75, loss = 5.98330274
Iteration 76, loss = 5.98218219
Iteration 77, loss = 5.98516939
Iteration 78, loss = 5.98178465
Iteration 79, loss = 5.99453462
Iteration 80, loss = 5.97835544
Iteration 81, loss = 5.99027399
Iteration 82, loss = 5.98184794
Iteration 83, loss = 5.98231713
Iteration 84, loss = 5.98809668
Iteration 85, loss = 5.98557242
Iteration 86, loss = 5.97691953
Iteration 87, loss = 5.98067501
Iteration 88, loss = 5.98524899
Iteration 89, loss = 5.97603937
Iteration 90, loss = 5.98947721
Iteration 91, loss = 5.97970567
Iteration 92, loss = 5.97400445
Iteration 93, loss = 5.97104861
Iteration 94, loss = 5.97926803
Iteration 95, loss = 5.96901671
Iteration 96, loss = 5.97339031
Iteration 97, loss = 5.96975666
Iteration 98, loss = 5.96864558
Iteration 99, loss = 5.97544595
Iteration 100, loss = 5.96593903
Iteration 101, loss = 5.97678824
Iteration 102, loss = 5.97374012
Iteration 103, loss = 5.96829333
Iteration 104, loss = 5.98172958
Iteration 105, loss = 5.96853553
Iteration 106, loss = 5.97251301
Iteration 107, loss = 5.96517054
Iteration 108, loss = 5.96787088
Iteration 109, loss = 5.97404570
Iteration 110, loss = 5.97321668
Iteration 111, loss = 5.97069682
Iteration 112, loss = 5.97117385
Iteration 113, loss = 5.96980113
Iteration 114, loss = 5.96719649
Iteration 115, loss = 5.96353016
Iteration 116, loss = 5.97126219
Iteration 117, loss = 5.96715515
Iteration 118, loss = 5.96292774
Iteration 119, loss = 5.96830829
Iteration 120, loss = 5.96385072
Iteration 121, loss = 5.96288889
Iteration 122, loss = 5.96166785
Iteration 123, loss = 5.97704369
Iteration 124, loss = 5.95708014
Iteration 125, loss = 5.96140358
Iteration 126, loss = 5.97343248
Iteration 127, loss = 5.95715131
Iteration 128, loss = 5.96432777
Iteration 129, loss = 5.96321153
Iteration 130, loss = 5.96015116
Iteration 131, loss = 5.96673663
Iteration 132, loss = 5.96117071
Iteration 133, loss = 5.96744197
Iteration 134, loss = 5.95653960
Iteration 135, loss = 5.96264822
Iteration 136, loss = 5.95272030
Iteration 137, loss = 5.95250838
Iteration 138, loss = 5.95444001
Iteration 139, loss = 5.95964825
Iteration 140, loss = 5.96205276
Iteration 141, loss = 5.95647911
Iteration 142, loss = 5.94954593
Iteration 143, loss = 5.95426000
Iteration 144, loss = 5.96235296
Iteration 145, loss = 5.95499385
Iteration 146, loss = 5.95325792
Iteration 147, loss = 5.94735353
Iteration 148, loss = 5.95305587
Iteration 149, loss = 5.95185971
Iteration 150, loss = 5.95915819
Iteration 151, loss = 5.94819090
Iteration 152, loss = 5.96898876
Iteration 153, loss = 5.95042789
Iteration 154, loss = 5.95457513
Iteration 155, loss = 5.94396672
Iteration 156, loss = 5.95284646
Iteration 157, loss = 5.95236706
Iteration 158, loss = 5.94128762
Iteration 159, loss = 5.94623254
Iteration 160, loss = 5.94885642
Iteration 161, loss = 5.95158619
Iteration 162, loss = 5.94824127
Iteration 163, loss = 5.94678685
Iteration 164, loss = 5.94980812
Iteration 165, loss = 5.94928179
Iteration 166, loss = 5.94517608
Iteration 167, loss = 5.94685511
Iteration 168, loss = 5.94807355
Iteration 169, loss = 5.95393285
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=True, warm_start=False)

In [29]:
pred = regressor.predict(x_train)
score = np.linalg.norm((y_train-pred)**2,ord=2)/pred.shape[0]
print(score)

0.11834901992622186

In [30]:
pred = regressor.predict(x_test)
score = np.linalg.norm((y_test-pred)**2,ord=2)/pred.shape[0]
print(score)

0.35516039102842706

In [31]:
months_of_activity_orig = d_raw['months_of_activity']

In [32]:
indx_nan = np.array(months_of_activity_orig.isna())
indx_nan = np.where(indx_nan == True)[0]
indx_not_nan = np.where(indx_nan == False)[0]

In [33]:
months_of_activity_pred = months_of_activity_orig
temp_data = np.array(d_raw.drop(['months_of_activity','pricing_category'],axis=1))[indx_nan,:]
print(temp_data.shape)
months_of_activity_pred[indx_nan] = regressor.predict(temp_data)

(3533, 34)

/home/supreet/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [34]:
print(d_raw.isnull().sum())

distance                         0
months_of_activity               0
customer_score                   0
ratings_given_by_cust            0
num_of_cancelled_trips           0
anon_var_2                       0
anon_var_3                       0
pricing_category                 0
taxi_type_A                      0
taxi_type_B                      0
taxi_type_C                      0
taxi_type_D                      0
taxi_type_E                      0
taxi_type_nan                    0
customer_score_confidence_A      0
customer_score_confidence_B      0
customer_score_confidence_C      0
customer_score_confidence_nan    0
drop_location_type_A             0
drop_location_type_B             0
drop_location_type_C             0
drop_location_type_D             0
drop_location_type_E             0
drop_location_type_F             0
drop_location_type_G             0
drop_location_type_H             0
drop_location_type_I             0
drop_location_type_J             0
drop_location_type_K             0
drop_location_type_L             0
drop_location_type_M             0
drop_location_type_N             0
drop_location_type_nan           0
sex_Female                       0
sex_Male                         0
sex_nan                          0
dtype: int64

In [35]:
d_raw1['anon_var_1'] = df_raw['anon_var_1'].copy(deep=True)
d_raw = d_raw1.copy(deep=True)

In [36]:
anon_var_1 = d_raw['anon_var_1']
anon_var_1 = anon_var_1.fillna(anon_var_1.mean())
d_raw['anon_var_1'] = anon_var_1

In [37]:
data = d_raw.drop(['anon_var_1','pricing_category'], axis=1)
label = d_raw['anon_var_1']

In [38]:
x_train, x_test, y_train, y_test = train_test_split(data, label, test_size = 0.1)

In [39]:
regressor_3 = MLPRegressor(verbose=True)
regressor_3.fit(x_train, y_train)

Iteration 1, loss = 165.48384544
Iteration 2, loss = 125.52333043
Iteration 3, loss = 121.14514572
Iteration 4, loss = 119.83313138
Iteration 5, loss = 118.54798874
Iteration 6, loss = 117.47489057
Iteration 7, loss = 116.19738771
Iteration 8, loss = 115.55100884
Iteration 9, loss = 114.47127943
Iteration 10, loss = 113.76996714
Iteration 11, loss = 113.00111240
Iteration 12, loss = 112.68419512
Iteration 13, loss = 112.28009690
Iteration 14, loss = 112.15233401
Iteration 15, loss = 111.59819215
Iteration 16, loss = 111.37697386
Iteration 17, loss = 111.41193281
Iteration 18, loss = 111.32853892
Iteration 19, loss = 111.08656421
Iteration 20, loss = 110.96380992
Iteration 21, loss = 110.90952419
Iteration 22, loss = 111.01011947
Iteration 23, loss = 110.49986690
Iteration 24, loss = 110.65224161
Iteration 25, loss = 110.70035618
Iteration 26, loss = 110.45296588
Iteration 27, loss = 110.55914892
Iteration 28, loss = 110.48288178
Iteration 29, loss = 110.43006941
Iteration 30, loss = 110.37260119
Iteration 31, loss = 110.40658490
Iteration 32, loss = 110.34168341
Iteration 33, loss = 110.28954463
Iteration 34, loss = 110.21248840
Iteration 35, loss = 110.14268984
Iteration 36, loss = 110.42921018
Iteration 37, loss = 110.28865429
Iteration 38, loss = 110.30573187
Iteration 39, loss = 110.38232585
Iteration 40, loss = 110.04835848
Iteration 41, loss = 110.07177552
Iteration 42, loss = 109.99594882
Iteration 43, loss = 109.80288473
Iteration 44, loss = 109.90540313
Iteration 45, loss = 110.13252518
Iteration 46, loss = 110.02573048
Iteration 47, loss = 109.99899893
Iteration 48, loss = 110.15606487
Iteration 49, loss = 109.88679217
Iteration 50, loss = 109.86183231
Iteration 51, loss = 109.82284061
Iteration 52, loss = 109.76257798
Iteration 53, loss = 109.70398677
Iteration 54, loss = 109.78326194
Iteration 55, loss = 109.83129495
Iteration 56, loss = 109.92003479
Iteration 57, loss = 109.59654636
Iteration 58, loss = 109.62397395
Iteration 59, loss = 109.48376687
Iteration 60, loss = 109.80405474
Iteration 61, loss = 109.82315021
Iteration 62, loss = 109.66122961
Iteration 63, loss = 109.61696042
Iteration 64, loss = 109.87936369
Iteration 65, loss = 109.73217481
Iteration 66, loss = 109.59418779
Iteration 67, loss = 109.70867358
Iteration 68, loss = 109.50188099
Iteration 69, loss = 109.72088678
Iteration 70, loss = 109.55414403
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=True, warm_start=False)

In [40]:
pred = regressor_3.predict(x_train)
score = np.linalg.norm((y_train-pred)**2,ord=2)/pred.shape[0]
print(score)

1.8297910928860537

In [41]:
pred = regressor_3.predict(x_test)
score = np.linalg.norm((y_test-pred)**2,ord=2)/pred.shape[0]
print(score)

5.451779390621888

In [42]:
anon_var_1_orig = d_raw1['anon_var_1']

In [43]:
indx_nan = np.array(anon_var_1_orig.isna())
indx_nan = np.where(indx_nan == True)[0]
indx_not_nan = np.where(indx_nan == False)[0]

In [44]:
d_raw

,distance,months_of_activity,customer_score,ratings_given_by_cust,num_of_cancelled_trips,anon_var_2,anon_var_3,pricing_category,taxi_type_A,taxi_type_B,...,drop_location_type_J,drop_location_type_K,drop_location_type_L,drop_location_type_M,drop_location_type_N,drop_location_type_nan,sex_Female,sex_Male,sex_nan,anon_var_1
0,59.30,1.000000,2.609415,1.18625,0,50,71,2,0,0,...,0,0,0,0,0,0,0,1,0,64.249768
1,20.68,0.000000,2.792220,1.91750,1,50,65,2,0,1,...,0,0,0,0,0,0,0,1,0,31.000000
2,64.83,1.000000,2.974820,3.62125,0,49,84,2,0,1,...,0,0,0,0,0,0,0,1,0,65.000000
3,25.51,0.000000,2.903340,4.76750,2,43,60,3,0,0,...,0,0,0,0,0,0,1,0,0,46.000000
4,20.16,6.000000,2.623010,2.03875,0,52,71,3,0,0,...,0,0,0,0,0,0,1,0,0,64.249768
5,16.07,0.000000,2.233150,2.61625,3,52,66,1,1,0,...,0,0,0,0,0,0,1,0,0,64.249768
6,62.67,5.000000,2.911950,2.70375,1,59,95,1,1,0,...,0,0,0,0,0,0,0,1,0,64.249768
7,61.80,10.000000,2.888190,2.90375,0,51,70,1,1,0,...,0,0,0,0,0,0,1,0,0,64.249768
8,50.22,10.000000,2.649320,2.32375,0,49,82,2,0,1,...,0,0,0,0,0,0,0,1,0,87.000000
9,47.68,2.000000,2.627130,3.85250,0,46,58,3,0,0,...,0,0,0,0,0,0,1,0,0,64.249768
10,47.79,2.000000,2.906980,1.39625,1,52,90,3,0,0,...,0,0,0,0,0,0,0,1,0,92.000000
11,18.25,5.000000,2.696020,1.86750,1,53,77,2,0,0,...,0,0,0,0,0,0,0,1,0,64.249768
12,91.61,10.000000,3.095250,4.12500,0,50,67,3,0,1,...,0,0,0,0,0,0,0,1,0,94.000000
13,90.96,10.000000,2.871346,1.62000,0,61,91,3,0,0,...,0,0,0,0,0,0,0,1,0,63.000000
14,63.03,3.000000,2.951380,3.06125,0,58,85,2,0,1,...,0,0,0,0,0,0,1,0,0,64.249768
15,28.28,10.000000,2.818620,2.92125,1,55,86,1,1,0,...,0,0,0,0,0,0,1,0,0,55.000000
16,16.97,10.000000,3.082210,1.50125,1,59,91,2,0,1,...,0,0,0,0,0,0,0,1,0,43.000000
17,75.37,0.000000,2.905380,4.21375,2,50,73,3,0,0,...,0,0,0,0,0,0,0,1,0,35.000000
18,81.73,10.000000,2.913180,2.92750,0,50,76,1,0,0,...,0,0,0,0,0,0,0,1,0,40.000000
19,30.00,6.014179,2.591920,2.72000,0,47,86,2,0,0,...,0,0,0,0,0,0,1,0,0,64.249768
20,30.34,2.000000,2.771530,4.40250,0,45,66,2,0,0,...,0,0,0,0,0,0,0,1,0,64.249768
21,3.47,5.000000,2.543270,1.27625,1,54,66,2,0,1,...,0,0,0,0,0,0,0,1,0,64.249768
22,27.32,9.000000,2.424150,2.71000,0,45,58,2,0,1,...,0,0,0,0,0,0,0,1,0,64.249768
23,29.90,3.000000,2.756829,3.01750,0,50,70,1,0,1,...,0,0,0,0,0,0,1,0,0,64.249768
24,54.37,2.000000,2.843720,2.02500,1,50,76,3,0,0,...,0,0,0,0,0,0,0,1,0,47.000000
25,30.79,0.000000,2.688737,1.48125,3,54,74,2,0,0,...,0,0,0,0,0,0,1,0,0,101.000000
26,31.38,10.000000,2.804790,0.82375,0,53,88,2,0,0,...,0,0,0,0,0,0,0,1,0,64.249768
27,29.65,10.000000,3.088260,2.71625,1,57,84,3,0,0,...,0,0,0,0,0,0,0,1,0,33.000000
28,33.14,10.000000,2.595710,2.46125,0,45,60,2,0,0,...,0,0,0,0,0,0,0,1,0,64.249768
29,55.14,10.000000,2.931830,1.04500,0,56,89,3,0,0,...,0,0,0,0,0,0,0,1,0,64.249768
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78967,10.47,6.000000,2.901640,2.86250,1,63,88,3,0,0,...,0,0,0,0,0,0,0,1,0,35.000000
78968,13.29,5.000000,2.693740,2.15875,3,56,95,2,0,0,...,0,0,0,0,0,0,0,1,0,34.000000
78969,43.50,6.000000,2.658690,1.38250,0,58,80,2,0,0,...,0,0,0,0,0,0,0,1,0,64.249768
78970,108.21,1.000000,3.603070,2.90000,0,56,97,3,0,0,...,0,0,0,0,0,0,0,1,0,31.000000
78971,92.94,6.000000,3.041098,3.62125,0,57,98,1,1,0,...,0,0,0,0,0,0,0,1,0,110.000000
78972,11.72,3.000000,3.037780,2.58750,1,58,86,2,0,0,...,0,0,0,0,0,0,0,1,0,64.249768
78973,63.65,10.000000,2.806930,3.60125,1,47,75,3,0,0,...,0,0,0,0,0,0,1,0,0,99.000000
78974,107.32,10.000000,3.131750,1.76250,0,62,92,3,0,0,...,0,0,0,0,0,0,1,0,0,64.249768
78975,50.75,10.000000,3.024010,2.81625,0,50,85,1,0,0,...,0,0,0,0,0,0,0,1,0,64.249768
78976,47.14,6.000000,2.854940,2.56625,5,53,73,2,0,0,...,0,0,0,0,0,0,0,1,0,64.249768
78977,36.84,0.000000,2.746830,2.88125,0,54,107,2,0,0,...,0,0,0,0,0,0,0,1,0,64.249768
78978,22.81,10.000000,2.536810,2.66000,0,49,65,2,0,1,...,0,0,0,0,0,0,1,0,0,64.249768
78979,108.14,10.000000,3.059610,3.95250,2,52,83,3,0,0,...,0,0,1,0,0,0,0,1,0,65.000000
78980,15.44,6.014179,2.665670,1.96500,0,47,74,2,0,0,...,0,0,0,0,0,0,1,0,0,48.000000
78981,23.18,3.000000,2.632180,1.73375,0,52,68,2,0,0,...,0,0,0,0,0,0,0,1,0,64.249768
78982,74.20,9.000000,2.961720,2.43875,0,55,100,1,1,0,...,0,0,0,0,0,0,0,1,0,64.249768
78983,4.67,4.000000,2.764480,3.31250,0,62,85,2,0,1,...,0,0,0,0,0,0,1,0,0,64.249768
78984,91.79,10.000000,3.023110,3.06875,1,48,61,3,1,0,...,0,0,0,0,0,0,1,0,0,64.249768
78985,57.19,5.000000,2.785980,2.68500,0,47,82,1,1,0,...,0,0,0,0,0,0,0,1,0,64.249768
78986,56.58,10.000000,3.100250,2.80375,0,49,75,2,0,1,...,0,0,0,0,0,0,1,0,0,64.249768
78987,42.25,6.000000,3.027730,2.42375,1,57,91,2,0,1,...,0,0,0,0,0,0,1,0,0,64.249768
78988,18.42,4.000000,2.604920,1.39250,2,53,81,2,0,0,...,0,0,0,0,0,0,1,0,0,59.000000
78989,62.06,10.000000,2.791330,3.96875,0,47,71,2,0,0,...,0,0,0,0,0,0,0,1,0,51.000000
78990,8.30,6.014179,2.320790,3.96500,0,47,61,3,0,0,...,0,0,0,0,0,0,0,1,0,71.000000
78991,69.29,10.000000,2.778870,1.59000,0,53,74,3,0,0,...,0,0,0,0,0,0,0,1,0,64.249768
78992,10.69,0.000000,2.386530,3.27250,0,44,68,2,0,1,...,0,0,0,0,0,0,0,1,0,55.000000
78993,31.58,10.000000,2.611040,1.41125,1,49,68,2,0,1,...,0,0,0,0,0,0,1,0,0,64.249768
78994,13.11,6.000000,2.653540,3.54375,0,48,63,2,0,1,...,0,0,0,0,0,0,0,1,0,64.249768
78995,63.79,10.000000,2.801226,3.60125,0,51,74,2,0,0,...,0,0,0,0,0,0,0,1,0,64.249768
78996,30.46,10.000000,2.743670,2.69250,1,48,64,3,0,0,...,0,0,0,0,0,0,0,1,0,94.000000

In [45]:
anon_var_1_pred = anon_var_1_orig
temp_data = np.array(d_raw.drop(['anon_var_1','pricing_category'],axis=1))[indx_nan,:]
print(temp_data.shape)
anon_var_1_pred[indx_nan] = regressor_3.predict(temp_data)

(42419, 35)

/home/supreet/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [46]:
print(d_raw1.isnull().sum())

distance                         0
months_of_activity               0
customer_score                   0
ratings_given_by_cust            0
num_of_cancelled_trips           0
anon_var_2                       0
anon_var_3                       0
pricing_category                 0
taxi_type_A                      0
taxi_type_B                      0
taxi_type_C                      0
taxi_type_D                      0
taxi_type_E                      0
taxi_type_nan                    0
customer_score_confidence_A      0
customer_score_confidence_B      0
customer_score_confidence_C      0
customer_score_confidence_nan    0
drop_location_type_A             0
drop_location_type_B             0
drop_location_type_C             0
drop_location_type_D             0
drop_location_type_E             0
drop_location_type_F             0
drop_location_type_G             0
drop_location_type_H             0
drop_location_type_I             0
drop_location_type_J             0
drop_location_type_K             0
drop_location_type_L             0
drop_location_type_M             0
drop_location_type_N             0
drop_location_type_nan           0
sex_Female                       0
sex_Male                         0
sex_nan                          0
anon_var_1                       0
dtype: int64

In [47]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

In [48]:
data = d_raw.drop(['pricing_category'], axis=1)
label = d_raw['pricing_category']

In [86]:
x_train, x_test, y_train, y_test = train_test_split(data, label, test_size = 0.3)

In [50]:
# clf = RandomForestClassifier(n_jobs=4, max_depth=12, n_estimators=100)
clf = GradientBoostingClassifier(verbose=True,)

In [51]:
clf.fit(x_train, y_train)

      Iter       Train Loss   Remaining Time
         1       64578.9618           18.44s
         2       61779.7641           18.17s
         3       59528.5851           17.99s
         4       57694.4344           17.89s
         5       56184.7531           17.74s
         6       54936.6642           17.54s
         7       53915.9835           17.36s
         8       53031.7268           17.23s
         9       52305.7700           17.07s
        10       51638.6114           16.95s
        20       48255.0027           15.30s
        30       46905.8981           13.66s
        40       46053.6987           11.85s
        50       45482.4619            9.95s
        60       45072.9422            7.92s
        70       44755.9440            5.89s
        80       44488.3074            3.88s
        90       44267.0640            1.92s
       100       44084.3989            0.00s

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              n_iter_no_change=None, presort='auto', random_state=None,
              subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=True, warm_start=False)

In [52]:
print(clf.score(x_train, y_train))
print(clf.score(x_test, y_test))

0.7028181717486589
0.7035443037974684

In [53]:
# data

In [54]:
df_test = pd.read_csv('test.csv')
df_test_raw = df_test.copy(deep=True)
df_test = pd.get_dummies(df_test, columns=['taxi_type', 'customer_score_confidence', 'drop_location_type', 'sex'], dummy_na=True)
df_test_id = df_test['id']
df_test = df_test.drop(['anon_var_1','id'],axis=1)
df_test1 = df_test.copy(deep=True)
print(df_test.shape)

(52665, 35)

In [55]:
print(df_test.isnull().sum())

distance                            0
months_of_activity               2387
customer_score                   8152
ratings_given_by_cust               0
num_of_cancelled_trips              0
anon_var_2                          0
anon_var_3                          0
taxi_type_A                         0
taxi_type_B                         0
taxi_type_C                         0
taxi_type_D                         0
taxi_type_E                         0
taxi_type_nan                       0
customer_score_confidence_A         0
customer_score_confidence_B         0
customer_score_confidence_C         0
customer_score_confidence_nan       0
drop_location_type_A                0
drop_location_type_B                0
drop_location_type_C                0
drop_location_type_D                0
drop_location_type_E                0
drop_location_type_F                0
drop_location_type_G                0
drop_location_type_H                0
drop_location_type_I                0
drop_location_type_J                0
drop_location_type_K                0
drop_location_type_L                0
drop_location_type_M                0
drop_location_type_N                0
drop_location_type_nan              0
sex_Female                          0
sex_Male                            0
sex_nan                             0
dtype: int64

In [56]:
months_of_activity_t = df_test['months_of_activity']
months_of_activity_t.fillna(months_of_activity.mean(), inplace=True)
df_test['months_of_activity'] = months_of_activity_t

In [57]:
customer_score_orig_t = df_test['customer_score']

indx_nan_t = np.array(customer_score_orig_t.isna())
indx_nan_t = np.where(indx_nan_t == True)[0]
indx_not_nan_t = np.where(indx_nan_t == False)[0]

customer_score_pred_t = customer_score_orig_t
temp_data_t = np.array(df_test.drop(['customer_score'],axis=1))[indx_nan_t,:]
customer_score_pred_t[indx_nan_t] = regressor.predict(temp_data_t)

/home/supreet/.local/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [58]:
df_test['months_of_activity'] = df_test1['months_of_activity']
print(df_test.isnull().sum())

distance                            0
months_of_activity               2387
customer_score                      0
ratings_given_by_cust               0
num_of_cancelled_trips              0
anon_var_2                          0
anon_var_3                          0
taxi_type_A                         0
taxi_type_B                         0
taxi_type_C                         0
taxi_type_D                         0
taxi_type_E                         0
taxi_type_nan                       0
customer_score_confidence_A         0
customer_score_confidence_B         0
customer_score_confidence_C         0
customer_score_confidence_nan       0
drop_location_type_A                0
drop_location_type_B                0
drop_location_type_C                0
drop_location_type_D                0
drop_location_type_E                0
drop_location_type_F                0
drop_location_type_G                0
drop_location_type_H                0
drop_location_type_I                0
drop_location_type_J                0
drop_location_type_K                0
drop_location_type_L                0
drop_location_type_M                0
drop_location_type_N                0
drop_location_type_nan              0
sex_Female                          0
sex_Male                            0
sex_nan                             0
dtype: int64

In [59]:
months_of_activity_orig_t = df_test['months_of_activity']

indx_nan_t = np.array(months_of_activity_orig_t.isna())
indx_nan_t = np.where(indx_nan_t == True)[0]
indx_not_nan_t = np.where(indx_nan_t == False)[0]
# print(indx_nan_t)
months_of_activity_pred_t = months_of_activity_orig_t
temp_data_t = np.array(df_test.drop(['months_of_activity'],axis=1))[indx_nan_t,:]
months_of_activity_pred_t[indx_nan_t] = regressor_2.predict(temp_data_t)

/home/supreet/.local/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [60]:
print(df_test.isnull().sum())

distance                         0
months_of_activity               0
customer_score                   0
ratings_given_by_cust            0
num_of_cancelled_trips           0
anon_var_2                       0
anon_var_3                       0
taxi_type_A                      0
taxi_type_B                      0
taxi_type_C                      0
taxi_type_D                      0
taxi_type_E                      0
taxi_type_nan                    0
customer_score_confidence_A      0
customer_score_confidence_B      0
customer_score_confidence_C      0
customer_score_confidence_nan    0
drop_location_type_A             0
drop_location_type_B             0
drop_location_type_C             0
drop_location_type_D             0
drop_location_type_E             0
drop_location_type_F             0
drop_location_type_G             0
drop_location_type_H             0
drop_location_type_I             0
drop_location_type_J             0
drop_location_type_K             0
drop_location_type_L             0
drop_location_type_M             0
drop_location_type_N             0
drop_location_type_nan           0
sex_Female                       0
sex_Male                         0
sex_nan                          0
dtype: int64

In [61]:
anon_var_1_orig_t = df_test_raw['anon_var_1']
df_test['anon_var_1'] = anon_var_1_orig_t

indx_nan_t = np.array(anon_var_1_orig_t.isna())
indx_nan_t = np.where(indx_nan_t == True)[0]
indx_not_nan_t = np.where(indx_nan_t == False)[0]
# print(indx_nan_t)
anon_var_1_pred_t = anon_var_1_orig_t
temp_data_t = np.array(df_test.drop(['anon_var_1'],axis=1))[indx_nan_t,:]
anon_var_1_pred_t[indx_nan_t] = regressor_3.predict(temp_data_t)
df_test['anon_var_1'] = anon_var_1_pred_t

/home/supreet/.local/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

In [62]:
# print(df_test.isnull().sum())
df_test

,distance,months_of_activity,customer_score,ratings_given_by_cust,num_of_cancelled_trips,anon_var_2,anon_var_3,taxi_type_A,taxi_type_B,taxi_type_C,...,drop_location_type_J,drop_location_type_K,drop_location_type_L,drop_location_type_M,drop_location_type_N,drop_location_type_nan,sex_Female,sex_Male,sex_nan,anon_var_1
0,36.30,5.000000,2.785739,2.37500,0,49,86,0,0,1,...,0,0,0,0,0,0,1,0,0,63.121703
1,22.56,5.000000,2.800980,2.30875,0,51,67,0,0,0,...,0,0,0,0,0,0,0,1,0,64.294794
2,75.09,8.000000,2.724012,3.54000,0,49,65,1,0,0,...,0,0,0,0,0,0,0,1,0,64.026708
3,59.44,8.000000,2.797372,2.86500,2,53,86,0,0,1,...,0,0,0,0,0,0,0,1,0,68.000000
4,109.21,10.000000,3.230560,2.70000,1,56,92,0,0,0,...,0,0,0,0,0,0,1,0,0,43.000000
5,53.04,10.000000,3.190530,4.00875,3,51,98,0,0,0,...,0,0,0,0,0,0,1,0,0,35.000000
6,107.21,10.000000,2.897350,4.58875,3,52,75,0,1,0,...,0,0,0,0,0,0,1,0,0,63.848984
7,72.26,10.000000,2.876070,3.64750,1,61,97,0,0,0,...,0,0,0,0,0,0,0,1,0,69.000000
8,77.63,10.000000,3.175690,2.23000,0,56,74,0,0,0,...,0,0,0,0,0,0,0,1,0,63.843563
9,23.73,3.000000,2.706820,4.27125,0,51,73,0,0,0,...,0,0,0,0,0,0,0,1,0,64.493959
10,55.50,10.000000,2.946940,0.89750,0,60,89,0,0,1,...,0,0,0,0,0,0,0,1,0,66.000000
11,31.13,1.000000,2.531870,1.87500,0,49,74,0,1,0,...,0,0,0,0,0,0,0,1,0,44.000000
12,62.42,5.000000,2.825800,2.18875,1,52,70,0,0,0,...,0,0,0,0,0,0,1,0,0,65.146303
13,69.80,5.000000,2.782040,1.31000,0,49,86,0,0,1,...,0,0,0,0,0,0,1,0,0,62.963503
14,46.75,10.000000,2.799022,3.85625,1,47,60,0,0,0,...,0,0,0,0,0,0,0,1,0,65.517298
15,21.89,5.000000,2.706640,3.03500,0,52,67,0,1,0,...,0,0,0,0,0,0,0,1,0,65.455839
16,106.42,7.000000,3.174470,2.63125,2,58,85,0,0,0,...,0,0,0,0,0,0,0,1,0,62.270858
17,23.16,10.000000,2.523430,3.16000,2,45,64,0,1,0,...,0,0,0,0,0,0,0,1,0,65.926733
18,30.43,2.000000,2.577200,2.55875,0,53,73,0,0,0,...,0,0,0,0,0,0,1,0,0,64.000000
19,75.65,10.000000,3.132280,2.78750,5,55,77,1,0,0,...,0,0,0,0,0,0,0,1,0,65.811223
20,18.15,3.000000,2.669440,4.16375,1,48,61,0,1,0,...,0,0,0,0,0,0,0,1,0,86.000000
21,18.80,7.000000,2.771205,2.58625,0,47,63,0,0,1,...,0,0,0,0,0,0,1,0,0,65.602131
22,6.26,10.000000,2.607000,1.82000,1,54,84,0,0,1,...,0,0,0,0,0,0,0,1,0,70.000000
23,101.62,7.000000,3.352290,2.45750,0,52,76,0,0,0,...,0,0,0,0,0,0,0,1,0,61.522939
24,17.62,4.000000,2.565200,2.78750,1,45,59,0,0,0,...,0,0,0,0,0,0,0,1,0,66.289355
25,44.06,2.000000,2.906040,3.12500,2,48,60,0,0,0,...,0,0,0,0,0,0,0,1,0,64.499078
26,14.25,1.000000,2.693300,2.44250,1,59,89,0,0,0,...,0,0,0,0,0,0,1,0,0,63.288356
27,29.95,3.000000,2.591740,2.67750,0,48,63,0,0,1,...,0,0,0,0,0,0,1,0,0,95.000000
28,73.87,10.000000,3.079510,3.44250,1,55,81,0,0,0,...,0,0,0,0,0,0,0,1,0,76.000000
29,47.03,10.000000,2.957230,2.47750,0,50,73,0,0,0,...,0,0,0,0,0,0,0,1,0,63.535098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52635,27.84,5.000000,2.595280,2.29875,0,59,76,0,0,1,...,0,0,0,0,0,0,0,1,0,65.524579
52636,24.89,8.000000,2.692350,3.64125,0,46,58,1,0,0,...,0,0,0,0,0,0,0,1,0,64.321407
52637,61.66,10.000000,2.696300,2.53000,1,58,74,0,0,0,...,0,0,0,0,0,0,0,1,0,63.270927
52638,42.35,10.000000,2.786140,2.64125,2,47,75,1,0,0,...,0,0,0,0,0,0,1,0,0,96.000000
52639,18.90,10.000000,2.802040,3.48125,1,48,70,1,0,0,...,0,0,0,0,0,0,0,1,0,37.000000
52640,13.58,0.000000,2.637380,3.01875,0,53,69,1,0,0,...,0,0,0,0,0,0,0,1,0,64.603974
52641,45.13,5.772930,2.568480,3.15250,0,55,76,1,0,0,...,0,0,0,0,0,0,0,1,0,65.856254
52642,55.60,6.416316,2.866520,2.06625,0,46,75,0,1,0,...,0,0,0,0,0,0,0,1,0,49.000000
52643,93.71,10.000000,2.994550,2.30375,0,55,84,0,0,1,...,0,0,0,0,0,0,0,1,0,61.574476
52644,12.59,10.000000,2.495820,3.38750,0,48,66,0,0,0,...,0,0,0,0,0,0,1,0,0,79.000000
52645,106.45,4.000000,2.954100,3.42625,0,55,98,0,1,0,...,0,0,0,0,0,0,0,1,0,59.434726
52646,19.67,0.000000,2.707440,4.75625,5,50,61,0,0,0,...,0,0,0,0,0,0,0,1,0,64.458908
52647,44.61,2.000000,2.622340,1.70625,3,51,69,0,0,0,...,0,0,0,0,0,0,1,0,0,64.806848
52648,15.48,4.000000,2.930270,2.44625,0,52,92,0,1,0,...,0,0,0,0,0,0,0,1,0,38.000000
52649,11.53,10.000000,3.081700,2.27375,0,47,79,0,0,0,...,0,0,0,0,0,0,1,0,0,66.000000
52650,48.38,2.000000,3.035350,2.74000,1,48,79,0,1,0,...,0,0,0,0,0,0,0,1,0,63.744994
52651,33.02,4.000000,2.638210,3.35250,0,46,75,0,0,0,...,0,0,0,0,0,0,1,0,0,64.475402
52652,38.79,2.000000,2.655720,2.55375,0,49,70,0,1,0,...,0,0,0,0,0,0,0,1,0,49.000000
52653,30.32,4.000000,2.591530,4.46750,1,45,59,1,0,0,...,0,0,0,0,0,0,0,1,0,64.557730
52654,33.98,3.000000,2.703250,2.65125,0,49,60,0,0,0,...,0,0,0,0,0,0,0,1,0,64.708628
52655,64.89,6.000000,2.773890,3.49500,2,47,67,1,0,0,...,0,0,0,0,0,0,0,1,0,65.445917
52656,21.05,10.000000,2.927680,3.94500,1,58,77,0,1,0,...,0,0,0,0,0,0,0,1,0,64.214335
52657,11.70,4.954234,2.245540,3.59125,0,46,60,0,1,0,...,0,0,0,0,0,0,0,1,0,98.000000
52658,26.76,4.000000,3.039700,2.61125,0,62,85,0,0,0,...,0,0,0,0,0,0,1,0,0,38.000000
52659,45.66,1.000000,2.744070,3.71750,2,45,80,0,0,1,...,0,0,0,0,0,0,0,1,0,58.000000
52660,18.92,7.000000,2.797645,3.78250,1,46,64,0,0,0,...,0,0,0,0,0,0,0,1,0,72.000000
52661,92.28,6.000000,3.077930,3.75625,2,48,75,0,0,0,...,0,0,0,0,0,0,0,1,0,64.000000
52662,20.34,4.000000,2.513230,3.84250,0,47,62,1,0,0,...,0,0,0,0,0,0,1,0,0,63.619624
52663,11.38,0.000000,2.538550,2.69375,2,49,63,0,0,0,...,0,0,0,0,0,0,0,1,0,64.897310
52664,100.79,10.000000,2.903470,2.98625,1,56,82,0,0,0,...,0,0,0,0,0,0,1,0,0,62.008440

In [63]:
testY_i = clf.predict(df_test)
print(testY_i.shape)
testY_s = []
for x in testY_i:
    testY_s.append(float(x))
# Write the predictions to a CSV file 
submission = pd.DataFrame(
    {'id': df_test_id, 'pricing_category': testY_s},
    columns = ['id', 'pricing_category'])
submission.to_csv('submission_grad_boost.csv', index = False)

(52665,)

# xgb

In [64]:
import xgboost as xgb

In [156]:
x_train, x_test, y_train, y_test = train_test_split(data, label, test_size = 0)

In [157]:
xgb_model = xgb.XGBClassifier(objective="multi:softprob", n_jobs=6
                              , booster='gbtree', learning_rate=0.1)

In [158]:
xgb_model.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=6, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [159]:
print(xgb_model.score(x_train, y_train))
print(xgb_model.score(x_test, y_test))

0.699431623985721
nan

/home/supreet/.local/lib/python3.6/site-packages/numpy/lib/function_base.py:392: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/home/supreet/.local/lib/python3.6/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

In [160]:
from sklearn.model_selection import RandomizedSearchCV

def report_best_scores(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.3f} (std: {1:.3f})".format(
                  results['mean_test_score'][candidate],
                  results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")

In [161]:
from scipy.stats import uniform, randint
params = {
    "colsample_bytree": uniform(0.7, 0.3),
    "gamma": uniform(0, 0.5),
    "learning_rate": uniform(0.03, 0.3), # default 0.1 
    "max_depth": randint(2, 6), # default 3
    "n_estimators": randint(100, 150), # default 100
    "subsample": uniform(0.6, 0.4)
}
search = RandomizedSearchCV(xgb_model, param_distributions=params, cv=3,  n_jobs=1, return_train_score=True)
search.fit(x_train, y_train)

RandomizedSearchCV(cv=3, error_score='raise-deprecating',
          estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=6, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1),
          fit_params=None, iid='warn', n_iter=10, n_jobs=1,
          param_distributions={'colsample_bytree': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f80c8f915c0>, 'gamma': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f80c90eb748>, 'learning_rate': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f80c90ebef0>, 'max_depth': <sci...x7f80c8f8fd30>, 'subsample': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f80c8f8f780>},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score=True, scoring=None, verbose=0)

In [162]:
report_best_scores(search.cv_results_, 1)

Model with rank: 1
Mean validation score: 0.702 (std: 0.002)
Parameters: {'colsample_bytree': 0.9974041391066333, 'gamma': 0.06850591879406065, 'learning_rate': 0.23675039087916408, 'max_depth': 4, 'n_estimators': 110, 'subsample': 0.8448649323991969}

In [133]:
xgb_model1 = xgb.XGBClassifier(objective="multi:softprob", n_jobs=6
                               , colsample_bytree=0.8784595125717604
                              , gamma=0.2607420158093975
                               ,learning_rate= 0.15946285320025186
                                ,max_depth=5,n_estimators=121
                               , subsample= 0.8451611467961675)

In [134]:
xgb_model1.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.8784595125717604, gamma=0.2607420158093975,
       learning_rate=0.15946285320025186, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=121, n_jobs=6,
       nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=0.8451611467961675)

In [135]:
xgb_model1.score(x_train, y_train)

0.7229135283618365

In [136]:
testY_i = xgb_model1.predict(df_test)
print(testY_i.shape)
testY_s = []
for x in testY_i:
    testY_s.append(float(x))
# Write the predictions to a CSV file 
submission = pd.DataFrame(
    {'id': df_test_id, 'pricing_category': testY_s},
    columns = ['id', 'pricing_category'])
submission.to_csv('submission_grad_boost.csv', index = False)

(52665,)

## without anon var 1

In [150]:
t1 = df_test.copy()
#print(x_train.shape)

In [151]:
xt1 = x_train.drop(['drop_location_type_B'], axis=1)
t1 = t1.drop(['drop_location_type_B'], axis=1)

In [154]:


from scipy.stats import uniform, randint
params = {
    "colsample_bytree": uniform(0.7, 0.3),
    "gamma": uniform(0, 0.5),
    "learning_rate": uniform(0.03, 0.3), # default 0.1 
    "max_depth": randint(2, 6), # default 3
    "n_estimators": randint(100, 150), # default 100
    "subsample": uniform(0.6, 0.4)
}
search = RandomizedSearchCV(xgb_model, param_distributions=params, cv=3,  n_jobs=1, return_train_score=True)
search.fit(xt1, label)

RandomizedSearchCV(cv=3, error_score='raise-deprecating',
          estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=6, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1),
          fit_params=None, iid='warn', n_iter=10, n_jobs=1,
          param_distributions={'colsample_bytree': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f80c9529160>, 'gamma': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f80c9a55438>, 'learning_rate': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f80c9905668>, 'max_depth': <sci...x7f80c836de48>, 'subsample': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f80c836d1d0>},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score=True, scoring=None, verbose=0)

In [155]:
report_best_scores(search.cv_results_, 1)

Model with rank: 1
Mean validation score: 0.431 (std: 0.000)
Parameters: {'colsample_bytree': 0.8713220409898069, 'gamma': 0.11515732719490096, 'learning_rate': 0.041786246347171235, 'max_depth': 2, 'n_estimators': 114, 'subsample': 0.9100615507935045}

In [ ]:
xgb_model2 = xgb.XGBClassifier(objective="multi:softprob", n_jobs=6 , 
                               colsample_bytree=0.8784595125717604 , 
                               gamma=0.2607420158093975 ,
                               learning_rate= 0.15946285320025186 ,
                               max_depth=5,n_estimators=121 , 
                               subsample= 0.8451611467961675)